name: "Bug报告"
description: "报告NMD的Bug"
labels: [new report, bug]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "检查是否是NMD的错误，而非其他原因。"
    options:
    - label: "我在最新版本的NMD尝试运行，但仍出现错误。"
      required: true
    - label: "我在Issues中搜索并确认了没有重复其他Issue。"
      required: true
    - label: "我仔细阅读了检查项，知道了这个选项不用勾选。"
      required: false
    - label: "我确认这不是NMD上游技术栈出现的问题。"
      required: false
- type: textarea
  id: "yml-2"
  attributes:
    label: 场景
    description: "描述你如何触发Bug"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 现象
    description: "NMD出现了什么错误"
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: 期望
    description: "你期望NMD作出的正确行为"
  validations:
    required: true
- type: textarea
  id: "yml-5"
  attributes:
    label: 环境
    description: "你的电脑的信息（如Windows11专业工作站版24H2）"
  validations:
    required: false
- type: textarea
  id: "yml-6"
  attributes:
    label: 附件
    description: "在这里上传日志/TraceBack等信息"
  validations:
    required: false